### ISSUE TITLE
Include restart-services in official Debian repository

### ISSUE THREAD

**Issue by m3nu** [tpo/debian-goodies#1]
Why is this script missing from the official version? After 2 years it should be tested enough, right? If I wanted to make unsupervised updates more reliable by restarting affected services, I would really want this script.

**Comment by tpo** [comment]
Hello Manuel,

On Wed, 9 Apr 2014, Manuel Riel wrote:

> Why is this script missing from the official version? After 2 years it 
> should be tested enough, right? If I wanted to make unsupervised
> updates more reliable by restarting affected services, I would really 
> want this script.

Sourcepole has been using the restart-services script on most of its 
servers (~20) and they have been working and were more or less trouble 
free.

If you want to have the script included in Debian's official 
debian-goodies repository, then please go to the 
http://bugs.debian.org/debian-goodies find my bug report there and kindly 
ask, if progress could be made in including restart-services in the 
debian-goodies package.

I'm on travels, internet connection is horrible, and I can not really work 
on this issue. So please, if you will, invest a bit of time and talk to 
the debian-goodies maintainers to move this issue forward.

Thanks,
*t

**Comment by m3nu** [comment]
On it. Last week's heartbleed bug should provide some new arguments. None of the Debian server-packages restarted properly after openssl-lib was updated. So even after automatic updated servers will stay vulnerable.
